name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.0.11
  uuid: ^3.0.5
  reorderable_grid: ^1.0.10
  settings_ui: ^2.0.2
  table_calendar: ^3.1.2
  flutter_speed_dial: ^6.0.0

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_tts: ^3.3.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.4.0
  flutter_login: ^5.0.0
  firebase_storage: ^11.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/Screenshot 2024-07-29 at 4.31.43â€¯PM.png
    - assets/board_info/board.json
    - assets/imgs/OneDrive_Folder_Icon.png
    - assets/imgs/sun.png
    - assets/board_info/pictograms.json
    - assets/temp_logo.jpg


